<?php
/**
 * SettlementApi
 * PHP version 7.4
 *
 * @category Class
 * @package  FriendsOfCE\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChannelEngine Merchant API
 *
 * ChannelEngine API for merchants
 *
 * The version of the OpenAPI document: 2.13.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FriendsOfCE\Merchant\ApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use FriendsOfCE\Merchant\ApiClient\ApiException;
use FriendsOfCE\Merchant\ApiClient\Configuration;
use FriendsOfCE\Merchant\ApiClient\HeaderSelector;
use FriendsOfCE\Merchant\ApiClient\ObjectSerializer;

/**
 * SettlementApi Class Doc Comment
 *
 * @category Class
 * @package  FriendsOfCE\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SettlementApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'settlementGetByFilter' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation settlementGetByFilter
     *
     * Get settelmets
     *
     * @param  int[] $channelIds Filter on channel id list. (optional)
     * @param  \DateTime $fromStartDate Filter on the start date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $toStartDate Filter on the start date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $fromEndDate Filter on the end date of the settlement in ChannelEngine, starting from this date. This date is inclusive. (optional)
     * @param  \DateTime $toEndDate Filter on the end date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $fromCreateDate Filter on the create date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $toCreateDate Filter on the create date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $fromUpdateDate Filter on the update date of the settlement in ChannelEngine, starting from this date. This date is inclusive. (optional)
     * @param  \DateTime $toUpdateDate Filter on the update date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  int $page The page to filter on. Starts at 1. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['settlementGetByFilter'] to see the possible values for this operation
     *
     * @throws \FriendsOfCE\Merchant\ApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \FriendsOfCE\Merchant\ApiClient\Model\CollectionOfMerchantReportsResponse
     */
    public function settlementGetByFilter($channelIds = null, $fromStartDate = null, $toStartDate = null, $fromEndDate = null, $toEndDate = null, $fromCreateDate = null, $toCreateDate = null, $fromUpdateDate = null, $toUpdateDate = null, $page = null, string $contentType = self::contentTypes['settlementGetByFilter'][0])
    {
        list($response) = $this->settlementGetByFilterWithHttpInfo($channelIds, $fromStartDate, $toStartDate, $fromEndDate, $toEndDate, $fromCreateDate, $toCreateDate, $fromUpdateDate, $toUpdateDate, $page, $contentType);
        return $response;
    }

    /**
     * Operation settlementGetByFilterWithHttpInfo
     *
     * Get settelmets
     *
     * @param  int[] $channelIds Filter on channel id list. (optional)
     * @param  \DateTime $fromStartDate Filter on the start date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $toStartDate Filter on the start date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $fromEndDate Filter on the end date of the settlement in ChannelEngine, starting from this date. This date is inclusive. (optional)
     * @param  \DateTime $toEndDate Filter on the end date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $fromCreateDate Filter on the create date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $toCreateDate Filter on the create date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $fromUpdateDate Filter on the update date of the settlement in ChannelEngine, starting from this date. This date is inclusive. (optional)
     * @param  \DateTime $toUpdateDate Filter on the update date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  int $page The page to filter on. Starts at 1. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['settlementGetByFilter'] to see the possible values for this operation
     *
     * @throws \FriendsOfCE\Merchant\ApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \FriendsOfCE\Merchant\ApiClient\Model\CollectionOfMerchantReportsResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function settlementGetByFilterWithHttpInfo($channelIds = null, $fromStartDate = null, $toStartDate = null, $fromEndDate = null, $toEndDate = null, $fromCreateDate = null, $toCreateDate = null, $fromUpdateDate = null, $toUpdateDate = null, $page = null, string $contentType = self::contentTypes['settlementGetByFilter'][0])
    {
        $request = $this->settlementGetByFilterRequest($channelIds, $fromStartDate, $toStartDate, $fromEndDate, $toEndDate, $fromCreateDate, $toCreateDate, $fromUpdateDate, $toUpdateDate, $page, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\FriendsOfCE\Merchant\ApiClient\Model\CollectionOfMerchantReportsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\FriendsOfCE\Merchant\ApiClient\Model\CollectionOfMerchantReportsResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\FriendsOfCE\Merchant\ApiClient\Model\CollectionOfMerchantReportsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\FriendsOfCE\Merchant\ApiClient\Model\CollectionOfMerchantReportsResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\FriendsOfCE\Merchant\ApiClient\Model\CollectionOfMerchantReportsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation settlementGetByFilterAsync
     *
     * Get settelmets
     *
     * @param  int[] $channelIds Filter on channel id list. (optional)
     * @param  \DateTime $fromStartDate Filter on the start date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $toStartDate Filter on the start date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $fromEndDate Filter on the end date of the settlement in ChannelEngine, starting from this date. This date is inclusive. (optional)
     * @param  \DateTime $toEndDate Filter on the end date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $fromCreateDate Filter on the create date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $toCreateDate Filter on the create date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $fromUpdateDate Filter on the update date of the settlement in ChannelEngine, starting from this date. This date is inclusive. (optional)
     * @param  \DateTime $toUpdateDate Filter on the update date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  int $page The page to filter on. Starts at 1. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['settlementGetByFilter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function settlementGetByFilterAsync($channelIds = null, $fromStartDate = null, $toStartDate = null, $fromEndDate = null, $toEndDate = null, $fromCreateDate = null, $toCreateDate = null, $fromUpdateDate = null, $toUpdateDate = null, $page = null, string $contentType = self::contentTypes['settlementGetByFilter'][0])
    {
        return $this->settlementGetByFilterAsyncWithHttpInfo($channelIds, $fromStartDate, $toStartDate, $fromEndDate, $toEndDate, $fromCreateDate, $toCreateDate, $fromUpdateDate, $toUpdateDate, $page, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation settlementGetByFilterAsyncWithHttpInfo
     *
     * Get settelmets
     *
     * @param  int[] $channelIds Filter on channel id list. (optional)
     * @param  \DateTime $fromStartDate Filter on the start date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $toStartDate Filter on the start date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $fromEndDate Filter on the end date of the settlement in ChannelEngine, starting from this date. This date is inclusive. (optional)
     * @param  \DateTime $toEndDate Filter on the end date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $fromCreateDate Filter on the create date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $toCreateDate Filter on the create date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $fromUpdateDate Filter on the update date of the settlement in ChannelEngine, starting from this date. This date is inclusive. (optional)
     * @param  \DateTime $toUpdateDate Filter on the update date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  int $page The page to filter on. Starts at 1. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['settlementGetByFilter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function settlementGetByFilterAsyncWithHttpInfo($channelIds = null, $fromStartDate = null, $toStartDate = null, $fromEndDate = null, $toEndDate = null, $fromCreateDate = null, $toCreateDate = null, $fromUpdateDate = null, $toUpdateDate = null, $page = null, string $contentType = self::contentTypes['settlementGetByFilter'][0])
    {
        $returnType = '\FriendsOfCE\Merchant\ApiClient\Model\CollectionOfMerchantReportsResponse';
        $request = $this->settlementGetByFilterRequest($channelIds, $fromStartDate, $toStartDate, $fromEndDate, $toEndDate, $fromCreateDate, $toCreateDate, $fromUpdateDate, $toUpdateDate, $page, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'settlementGetByFilter'
     *
     * @param  int[] $channelIds Filter on channel id list. (optional)
     * @param  \DateTime $fromStartDate Filter on the start date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $toStartDate Filter on the start date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $fromEndDate Filter on the end date of the settlement in ChannelEngine, starting from this date. This date is inclusive. (optional)
     * @param  \DateTime $toEndDate Filter on the end date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $fromCreateDate Filter on the create date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $toCreateDate Filter on the create date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  \DateTime $fromUpdateDate Filter on the update date of the settlement in ChannelEngine, starting from this date. This date is inclusive. (optional)
     * @param  \DateTime $toUpdateDate Filter on the update date of the settlement in ChannelEngine, until this date. This date is exclusive. (optional)
     * @param  int $page The page to filter on. Starts at 1. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['settlementGetByFilter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function settlementGetByFilterRequest($channelIds = null, $fromStartDate = null, $toStartDate = null, $fromEndDate = null, $toEndDate = null, $fromCreateDate = null, $toCreateDate = null, $fromUpdateDate = null, $toUpdateDate = null, $page = null, string $contentType = self::contentTypes['settlementGetByFilter'][0])
    {












        $resourcePath = '/v2/settlements';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $channelIds,
            'channelIds', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fromStartDate,
            'fromStartDate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $toStartDate,
            'toStartDate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fromEndDate,
            'fromEndDate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $toEndDate,
            'toEndDate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fromCreateDate,
            'fromCreateDate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $toCreateDate,
            'toCreateDate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fromUpdateDate,
            'fromUpdateDate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $toUpdateDate,
            'toUpdateDate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $queryParams['apikey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
