<?php
/**
 * MerchantOrderServiceLineResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FriendsOfCE\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChannelEngine Merchant API
 *
 * ChannelEngine API for merchants
 *
 * The version of the OpenAPI document: 2.22.12
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FriendsOfCE\Merchant\ApiClient\Model;

use \ArrayAccess;
use \FriendsOfCE\Merchant\ApiClient\ObjectSerializer;

/**
 * MerchantOrderServiceLineResponse Class Doc Comment
 *
 * @category Class
 * @package  FriendsOfCE\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MerchantOrderServiceLineResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MerchantOrderServiceLineResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'type' => 'string',
        'originalAmountInclTax' => 'float',
        'originalAmountTax' => 'float',
        'amountInclTax' => 'float',
        'amountTax' => 'float',
        'taxRate' => 'float',
        'description' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int32',
        'type' => null,
        'originalAmountInclTax' => 'decimal',
        'originalAmountTax' => 'decimal',
        'amountInclTax' => 'decimal',
        'amountTax' => 'decimal',
        'taxRate' => 'decimal',
        'description' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'type' => false,
        'originalAmountInclTax' => false,
        'originalAmountTax' => false,
        'amountInclTax' => false,
        'amountTax' => false,
        'taxRate' => false,
        'description' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'Id',
        'type' => 'Type',
        'originalAmountInclTax' => 'OriginalAmountInclTax',
        'originalAmountTax' => 'OriginalAmountTax',
        'amountInclTax' => 'AmountInclTax',
        'amountTax' => 'AmountTax',
        'taxRate' => 'TaxRate',
        'description' => 'Description'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'type' => 'setType',
        'originalAmountInclTax' => 'setOriginalAmountInclTax',
        'originalAmountTax' => 'setOriginalAmountTax',
        'amountInclTax' => 'setAmountInclTax',
        'amountTax' => 'setAmountTax',
        'taxRate' => 'setTaxRate',
        'description' => 'setDescription'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'type' => 'getType',
        'originalAmountInclTax' => 'getOriginalAmountInclTax',
        'originalAmountTax' => 'getOriginalAmountTax',
        'amountInclTax' => 'getAmountInclTax',
        'amountTax' => 'getAmountTax',
        'taxRate' => 'getTaxRate',
        'description' => 'getDescription'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_DISCOUNT = 'DISCOUNT';
    public const TYPE_SHIPPING_COST = 'SHIPPING_COST';
    public const TYPE_GIFT_WRAP = 'GIFT_WRAP';
    public const TYPE_SERVICE_FEE = 'SERVICE_FEE';
    public const TYPE_ROUNDING_DIFFERENCE = 'ROUNDING_DIFFERENCE';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_DISCOUNT,
            self::TYPE_SHIPPING_COST,
            self::TYPE_GIFT_WRAP,
            self::TYPE_SERVICE_FEE,
            self::TYPE_ROUNDING_DIFFERENCE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('originalAmountInclTax', $data ?? [], null);
        $this->setIfExists('originalAmountTax', $data ?? [], null);
        $this->setIfExists('amountInclTax', $data ?? [], null);
        $this->setIfExists('amountTax', $data ?? [], null);
        $this->setIfExists('taxRate', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id The unique identifier used by ChannelEngine.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type The type of order service line.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets originalAmountInclTax
     *
     * @return float|null
     */
    public function getOriginalAmountInclTax()
    {
        return $this->container['originalAmountInclTax'];
    }

    /**
     * Sets originalAmountInclTax
     *
     * @param float|null $originalAmountInclTax The original amount including tax. This is the marketplace's original amount, in the marketplace's currency.
     *
     * @return self
     */
    public function setOriginalAmountInclTax($originalAmountInclTax)
    {
        if (is_null($originalAmountInclTax)) {
            throw new \InvalidArgumentException('non-nullable originalAmountInclTax cannot be null');
        }
        $this->container['originalAmountInclTax'] = $originalAmountInclTax;

        return $this;
    }

    /**
     * Gets originalAmountTax
     *
     * @return float|null
     */
    public function getOriginalAmountTax()
    {
        return $this->container['originalAmountTax'];
    }

    /**
     * Sets originalAmountTax
     *
     * @param float|null $originalAmountTax The original amount of tax. This is the marketplace's original amount, in the marketplace's currency.
     *
     * @return self
     */
    public function setOriginalAmountTax($originalAmountTax)
    {
        if (is_null($originalAmountTax)) {
            throw new \InvalidArgumentException('non-nullable originalAmountTax cannot be null');
        }
        $this->container['originalAmountTax'] = $originalAmountTax;

        return $this;
    }

    /**
     * Gets amountInclTax
     *
     * @return float|null
     */
    public function getAmountInclTax()
    {
        return $this->container['amountInclTax'];
    }

    /**
     * Sets amountInclTax
     *
     * @param float|null $amountInclTax The amount including tax. This is the amount in the tenant's currency.
     *
     * @return self
     */
    public function setAmountInclTax($amountInclTax)
    {
        if (is_null($amountInclTax)) {
            throw new \InvalidArgumentException('non-nullable amountInclTax cannot be null');
        }
        $this->container['amountInclTax'] = $amountInclTax;

        return $this;
    }

    /**
     * Gets amountTax
     *
     * @return float|null
     */
    public function getAmountTax()
    {
        return $this->container['amountTax'];
    }

    /**
     * Sets amountTax
     *
     * @param float|null $amountTax The amount of tax. This is the amount in the tenant's currency.
     *
     * @return self
     */
    public function setAmountTax($amountTax)
    {
        if (is_null($amountTax)) {
            throw new \InvalidArgumentException('non-nullable amountTax cannot be null');
        }
        $this->container['amountTax'] = $amountTax;

        return $this;
    }

    /**
     * Gets taxRate
     *
     * @return float|null
     */
    public function getTaxRate()
    {
        return $this->container['taxRate'];
    }

    /**
     * Sets taxRate
     *
     * @param float|null $taxRate The tax rate as a percentage.
     *
     * @return self
     */
    public function setTaxRate($taxRate)
    {
        if (is_null($taxRate)) {
            throw new \InvalidArgumentException('non-nullable taxRate cannot be null');
        }
        $this->container['taxRate'] = $taxRate;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description A description of the order service line.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


