<?php
/**
 * ReturnSupport
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FriendsOfCE\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChannelEngine Merchant API
 *
 * ChannelEngine API for merchants
 *
 * The version of the OpenAPI document: 2.22.12
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FriendsOfCE\Merchant\ApiClient\Model;

use \ArrayAccess;
use \FriendsOfCE\Merchant\ApiClient\ObjectSerializer;

/**
 * ReturnSupport Class Doc Comment
 *
 * @category Class
 * @package  FriendsOfCE\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ReturnSupport implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ReturnSupport';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'supportLevel' => 'string',
        'creatorSupport' => 'string',
        'supportedHandlingActions' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'supportLevel' => null,
        'creatorSupport' => null,
        'supportedHandlingActions' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'supportLevel' => false,
        'creatorSupport' => false,
        'supportedHandlingActions' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'supportLevel' => 'SupportLevel',
        'creatorSupport' => 'CreatorSupport',
        'supportedHandlingActions' => 'SupportedHandlingActions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'supportLevel' => 'setSupportLevel',
        'creatorSupport' => 'setCreatorSupport',
        'supportedHandlingActions' => 'setSupportedHandlingActions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'supportLevel' => 'getSupportLevel',
        'creatorSupport' => 'getCreatorSupport',
        'supportedHandlingActions' => 'getSupportedHandlingActions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const SUPPORT_LEVEL_NONE = 'NONE';
    public const SUPPORT_LEVEL_SUPPORT = 'SUPPORT';
    public const CREATOR_SUPPORT_ONLY_MERCHANT = 'ONLY_MERCHANT';
    public const CREATOR_SUPPORT_ONLY_CHANNEL = 'ONLY_CHANNEL';
    public const CREATOR_SUPPORT_BOTH = 'BOTH';
    public const SUPPORTED_HANDLING_ACTIONS_REFUND = 'REFUND';
    public const SUPPORTED_HANDLING_ACTIONS_EXCHANGE = 'EXCHANGE';
    public const SUPPORTED_HANDLING_ACTIONS_REPAIR = 'REPAIR';
    public const SUPPORTED_HANDLING_ACTIONS_KEEP = 'KEEP';
    public const SUPPORTED_HANDLING_ACTIONS_REJECT = 'REJECT';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSupportLevelAllowableValues()
    {
        return [
            self::SUPPORT_LEVEL_NONE,
            self::SUPPORT_LEVEL_SUPPORT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCreatorSupportAllowableValues()
    {
        return [
            self::CREATOR_SUPPORT_ONLY_MERCHANT,
            self::CREATOR_SUPPORT_ONLY_CHANNEL,
            self::CREATOR_SUPPORT_BOTH,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSupportedHandlingActionsAllowableValues()
    {
        return [
            self::SUPPORTED_HANDLING_ACTIONS_REFUND,
            self::SUPPORTED_HANDLING_ACTIONS_EXCHANGE,
            self::SUPPORTED_HANDLING_ACTIONS_REPAIR,
            self::SUPPORTED_HANDLING_ACTIONS_KEEP,
            self::SUPPORTED_HANDLING_ACTIONS_REJECT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('supportLevel', $data ?? [], null);
        $this->setIfExists('creatorSupport', $data ?? [], null);
        $this->setIfExists('supportedHandlingActions', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getSupportLevelAllowableValues();
        if (!is_null($this->container['supportLevel']) && !in_array($this->container['supportLevel'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'supportLevel', must be one of '%s'",
                $this->container['supportLevel'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getCreatorSupportAllowableValues();
        if (!is_null($this->container['creatorSupport']) && !in_array($this->container['creatorSupport'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'creatorSupport', must be one of '%s'",
                $this->container['creatorSupport'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets supportLevel
     *
     * @return string|null
     */
    public function getSupportLevel()
    {
        return $this->container['supportLevel'];
    }

    /**
     * Sets supportLevel
     *
     * @param string|null $supportLevel supportLevel
     *
     * @return self
     */
    public function setSupportLevel($supportLevel)
    {
        if (is_null($supportLevel)) {
            throw new \InvalidArgumentException('non-nullable supportLevel cannot be null');
        }
        $allowedValues = $this->getSupportLevelAllowableValues();
        if (!in_array($supportLevel, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'supportLevel', must be one of '%s'",
                    $supportLevel,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['supportLevel'] = $supportLevel;

        return $this;
    }

    /**
     * Gets creatorSupport
     *
     * @return string|null
     */
    public function getCreatorSupport()
    {
        return $this->container['creatorSupport'];
    }

    /**
     * Sets creatorSupport
     *
     * @param string|null $creatorSupport creatorSupport
     *
     * @return self
     */
    public function setCreatorSupport($creatorSupport)
    {
        if (is_null($creatorSupport)) {
            throw new \InvalidArgumentException('non-nullable creatorSupport cannot be null');
        }
        $allowedValues = $this->getCreatorSupportAllowableValues();
        if (!in_array($creatorSupport, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'creatorSupport', must be one of '%s'",
                    $creatorSupport,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['creatorSupport'] = $creatorSupport;

        return $this;
    }

    /**
     * Gets supportedHandlingActions
     *
     * @return string[]|null
     */
    public function getSupportedHandlingActions()
    {
        return $this->container['supportedHandlingActions'];
    }

    /**
     * Sets supportedHandlingActions
     *
     * @param string[]|null $supportedHandlingActions supportedHandlingActions
     *
     * @return self
     */
    public function setSupportedHandlingActions($supportedHandlingActions)
    {
        if (is_null($supportedHandlingActions)) {
            array_push($this->openAPINullablesSetToNull, 'supportedHandlingActions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('supportedHandlingActions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getSupportedHandlingActionsAllowableValues();
        if (!is_null($supportedHandlingActions) && array_diff($supportedHandlingActions, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'supportedHandlingActions', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['supportedHandlingActions'] = $supportedHandlingActions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


