<?php
/**
 * MerchantProductExtraDataItemResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FriendsOfCE\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChannelEngine Merchant API
 *
 * ChannelEngine API for merchants
 *
 * The version of the OpenAPI document: 2.13.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FriendsOfCE\Merchant\ApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MerchantProductExtraDataItemResponseTest Class Doc Comment
 *
 * @category    Class
 * @description MerchantProductExtraDataItemResponse
 * @package     FriendsOfCE\Merchant\ApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MerchantProductExtraDataItemResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MerchantProductExtraDataItemResponse"
     */
    public function testMerchantProductExtraDataItemResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "key"
     */
    public function testPropertyKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "isPublic"
     */
    public function testPropertyIsPublic()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "languageIsoCode"
     */
    public function testPropertyLanguageIsoCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
