<?php
/**
 * MerchantChannelLabelShipmentRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FriendsOfCE\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChannelEngine Merchant API
 *
 * ChannelEngine API for merchants
 *
 * The version of the OpenAPI document: 2.15.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FriendsOfCE\Merchant\ApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MerchantChannelLabelShipmentRequestTest Class Doc Comment
 *
 * @category    Class
 * @description MerchantChannelLabelShipmentRequest
 * @package     FriendsOfCE\Merchant\ApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MerchantChannelLabelShipmentRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MerchantChannelLabelShipmentRequest"
     */
    public function testMerchantChannelLabelShipmentRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dimensions"
     */
    public function testPropertyDimensions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "channelMethodCode"
     */
    public function testPropertyChannelMethodCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "merchantShipmentNo"
     */
    public function testPropertyMerchantShipmentNo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "merchantOrderNo"
     */
    public function testPropertyMerchantOrderNo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shippedFromCountryCode"
     */
    public function testPropertyShippedFromCountryCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shippedFromStockLocationId"
     */
    public function testPropertyShippedFromStockLocationId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "lines"
     */
    public function testPropertyLines()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
