<?php
/**
 * ProductAttributeGroupApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  FriendsOfCE\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChannelEngine Merchant API
 *
 * ChannelEngine API for merchants
 *
 * The version of the OpenAPI document: 2.13.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace FriendsOfCE\Merchant\ApiClient\Test\Api;

use \FriendsOfCE\Merchant\ApiClient\Configuration;
use \FriendsOfCE\Merchant\ApiClient\ApiException;
use \FriendsOfCE\Merchant\ApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductAttributeGroupApiTest Class Doc Comment
 *
 * @category Class
 * @package  FriendsOfCE\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductAttributeGroupApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productAttributeGroupAddProductExtraData
     *
     * Adds custom attributes to a group.
     *
     */
    public function testProductAttributeGroupAddProductExtraData()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productAttributeGroupCreate
     *
     * Creates a custom attribute group.
     *
     */
    public function testProductAttributeGroupCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productAttributeGroupDelete
     *
     * Deletes a custom attribute group.
     *
     */
    public function testProductAttributeGroupDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productAttributeGroupGetByFilter
     *
     * Gets custom attribute groups.
     *
     */
    public function testProductAttributeGroupGetByFilter()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productAttributeGroupGetWithChannelsByFilter
     *
     * Gets custom attribute groups and linked marketplaces.
     *
     */
    public function testProductAttributeGroupGetWithChannelsByFilter()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productAttributeGroupRemoveProductExtraData
     *
     * Deletes custom attributes from a group.
     *
     */
    public function testProductAttributeGroupRemoveProductExtraData()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productAttributeGroupRenameProductAttributeGroup
     *
     * Renames custom attribute groups.
     *
     */
    public function testProductAttributeGroupRenameProductAttributeGroup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
