<?php
/**
 * ReturnApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  FriendsOfCE\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChannelEngine Merchant API
 *
 * ChannelEngine API for merchants
 *
 * The version of the OpenAPI document: 2.14.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace FriendsOfCE\Merchant\ApiClient\Test\Api;

use \FriendsOfCE\Merchant\ApiClient\Configuration;
use \FriendsOfCE\Merchant\ApiClient\ApiException;
use \FriendsOfCE\Merchant\ApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReturnApiTest Class Doc Comment
 *
 * @category Class
 * @package  FriendsOfCE\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReturnApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for returnAcknowledge
     *
     * Acknowledges a return.
     *
     */
    public function testReturnAcknowledge()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for returnDeclareForMerchant
     *
     * Creates merchant return.
     *
     */
    public function testReturnDeclareForMerchant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for returnGetByMerchantOrderNo
     *
     * Gets a return.
     *
     */
    public function testReturnGetByMerchantOrderNo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for returnGetDeclaredByChannel
     *
     * Gets marketplace returns.
     *
     */
    public function testReturnGetDeclaredByChannel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for returnGetReturns
     *
     * Gets returns by filter.
     *
     */
    public function testReturnGetReturns()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for returnGetUnhandled
     *
     * Gets unhandled returns.
     *
     */
    public function testReturnGetUnhandled()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for returnUpdateForMerchant
     *
     * Marks returns as received.
     *
     */
    public function testReturnUpdateForMerchant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
