<?php
/**
 * SettlementsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  FriendsOfCE\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChannelEngine Merchant API
 *
 * ChannelEngine API for merchants
 *
 * The version of the OpenAPI document: 2.15.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace FriendsOfCE\Merchant\ApiClient\Test\Api;

use \FriendsOfCE\Merchant\ApiClient\Configuration;
use \FriendsOfCE\Merchant\ApiClient\ApiException;
use \FriendsOfCE\Merchant\ApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SettlementsApiTest Class Doc Comment
 *
 * @category Class
 * @package  FriendsOfCE\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SettlementsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for settlementGetByFilter
     *
     * Gets settlements.
     *
     */
    public function testSettlementGetByFilter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for settlementUploadSettlement
     *
     * Imports a settlement file..
     *
     */
    public function testSettlementUploadSettlement()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
